/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"
#include "clock.h"
#include "timer.h"
#include "led.h"

/*TODOs
 * - Enable UARTs for CLI
 * - Enable the CLI
 * -
 */

int main(void)
{
	clock_init();
	init_leds();
	tim4_output_compare();

}
